name: Generate Snake

# Controls when the action will run
on:
  # This workflow runs once a day automatically
  schedule:
    - cron: "0 0 * * *" 
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# The sequence of tasks that will be executed
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed
    steps:
    # Checks-out your repository
    - uses: actions/checkout@v2
    
    - uses: platane/snk@v3
      with:
        # Your GitHub username
        github_user_name: ${{ github.repository_owner }}
        
        # This determines where the files are saved
        outputs: |
          dist/github-contribution-grid-snake.svg
          dist/github-contribution-grid-snake-dark.svg
          dist/ocean.gif
          
    # Push the generated files to the repository
    - name: Push to GitHub
      uses: EndBug/add-and-commit@v9
      with:
        message: 'Generate Snake'
        add: 'dist/*.svg'
